### ISSUE TITLE
Error in 3d mode.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/neii-viewer#139] opened 2020-02-26 01:08 UTC
There is an error when viewing this item in 3d mode:

http://neiiviewer.nicta.com.au/#share=s-OtZ0l5w6WZg04zFDO5bjkyYANV

**Comment by martin-bom** [comment] 2020-03-06 00:15
I tried the URL. no dataset is added and no error pops up. Can you tell me which dataset you selected in the 3D mode which showed that error?

**Comment by na9da** [comment] 2020-03-13 00:13
Sorry! proper link here - http://neiiviewer.nicta.com.au/#share=s-32VI2GosR94ddbuWmo8Fkefbm0M

**Comment by martin-bom** [comment] 2020-03-16 03:31
The issue is similar to:
https://nationalmap.gov.au/#clean&https://gist.githubusercontent.com/kring/600bf12e9b724e3dafbcf958452839d5/raw/4fe9e4b0a9b21494f2ec7840b3fc783f09c6ea79/rekt.json

which was mentioned in TerriaJS project:
https://github.com/TerriaJS/terriajs/issues/723

**Comment by martin-bom** [comment] 2020-03-31 01:51
It comes up that the attribute "rectangle" that causes the issue. By removing the attribute the layer can be displayed properly in 3D mode.

**Comment by martin-bom** [comment] 2020-04-21 00:14
Hello @na9da , it seems to be working now by removing the rectangle parameter. You can try again by going to the http://neiiviewer.nicta.com.au/

**Comment by na9da** [comment] 2020-04-21 23:35
Strange that the second link I posted is also not working.
The data set, If I recall correctly was - 
'Oceans > Marine Water Quality > Annual Median > Cholorophyll-a Concentration'

That seems to be working and the error is gone. So all good :+1:

**Comment by martin-bom** [comment] 2020-04-22 05:17
Commit: https://github.com/TerriaJS/neii-viewer/commit/273325573ec1223a5df796e75ff6068398801e58

Close the issue by now.

**Closed by martin-bom** 2020-04-22 05:17 UTC
