### ISSUE TITLE
Staging Viewer returning error

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#31] opened 2016-06-27 04:10 UTC
Hi Steve,

Did you have a chance to investigate the error on the Staging Viewer?  I checked this morning and am getting the below error.
http://nationalmap.research.nicta.com.au/neii/

Error Message when opening Staging Viewer:
TerriaJS App experienced an error. Please report this by emailing support@terria.io. Details of the error are below.
SyntaxError: Unexpected token < in JSON at position 

Thanks,
Chantelle

**Comment by stevage** [comment] 2016-06-27 05:08
Fixed now - it was caused by a short term fix I made directly on the server (modifying config.json), which conflict with a change that I think you made to the same file.

**Closed by stevage** 2016-06-27 05:08 UTC

**Comment by ChantelleDoan** [comment] 2016-06-27 06:40
Thanks @stevage.  It is now working on Chrome for me but I get the following errors in Firefox and IE:
•	Windows Chrome:  Works ok
•	Windows Firefox:  SyntaxError: JSON.parse: expected property name or '}' at line 2 column 1 of the JSON data
•	Windows IE:  SyntaxError: Invalid character

**Comment by stevage** [comment] 2016-06-27 07:12
Ok, here's my interpretation:

Windows Chrome: Works ok
Windows Firefox: Still showing cached version
Windows IE: Still showing cached version
